'use client';

import { BedDouble, Check, Clock3, Filter, Plane, Search, Ticket, TrainFront } from 'lucide-react';
import { useState } from 'react';
import type { Booking, BookingStatus } from '@/lib/types';

const filters = ['All','Need to Book','Booked','Paid','Cancelled'] as const;
const icons: Record<string, typeof Plane> = { Flight:Plane, Accommodation:BedDouble, 'High-speed train':TrainFront, Attraction:Ticket };

export function BookingsView({ initialBookings }: { initialBookings: Booking[] }) {
  const [bookings,setBookings]=useState(initialBookings); const [filter,setFilter]=useState<(typeof filters)[number]>('All'); const [query,setQuery]=useState('');
  const shown=bookings.filter((booking)=>(filter==='All'||booking.status===filter)&&booking.title.toLowerCase().includes(query.toLowerCase()));
  const update=(id:string,status:BookingStatus)=>setBookings((items)=>items.map((item)=>item.id===id?{...item,status}:item));
  return <div className="bookings-view"><div className="view-title"><div><p className="eyebrow">BOOKING CONTROL</p><h2>Everything that needs a yes</h2><p>{bookings.filter((b)=>['Booked','Paid'].includes(b.status)).length} of {bookings.length} reservations confirmed.</p></div><button className="primary-button">＋ Add booking</button></div><div className="booking-summary"><div><span className="summary-icon done"><Check size={18}/></span><p>Confirmed<strong>{bookings.filter((b)=>['Booked','Paid'].includes(b.status)).length}</strong></p></div><div><span className="summary-icon pending"><Clock3 size={18}/></span><p>Need attention<strong>{bookings.filter((b)=>['Need to Book','Shortlisted'].includes(b.status)).length}</strong></p></div><div className="booking-progress"><span>Booking progress</span><div><i style={{width:`${bookings.filter((b)=>['Booked','Paid'].includes(b.status)).length/bookings.length*100}%`}}/></div><strong>57%</strong></div></div><div className="booking-tools"><div className="booking-filters" role="tablist">{filters.map((item)=><button key={item} type="button" className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}{item==='Need to Book'&&<span>{bookings.filter((b)=>b.status==='Need to Book').length}</span>}</button>)}</div><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search bookings"/><Filter size={14}/></label></div><div className="booking-list"><div className="booking-list-head"><span>Booking</span><span>Status</span><span>Payment</span><span>Cost</span><span/></div>{shown.map((booking)=>{const Icon=icons[booking.category]??Ticket;return <article key={booking.id}><div className="booking-name"><span><Icon size={17}/></span><div><strong>{booking.title}</strong><small>{booking.category}{booking.provider?` · ${booking.provider}`:''}{booking.reference?` · ${booking.reference}`:''}</small></div></div><select value={booking.status} aria-label={`Status for ${booking.title}`} onChange={(e)=>update(booking.id,e.target.value as BookingStatus)}><option>Researching</option><option>Shortlisted</option><option>Need to Book</option><option>Reserved</option><option>Booked</option><option>Paid</option><option>Cancelled</option></select><span className="payment-text">{booking.paymentStatus}</span><strong>A${booking.cost.toLocaleString()}</strong><button type="button" aria-label={`Open ${booking.title}`}>›</button>{(booking.deadline||booking.cancellationDeadline)&&<p className="booking-deadline"><Clock3 size={12}/>{booking.deadline??booking.cancellationDeadline}</p>}</article>})}{shown.length===0&&<div className="empty-inline"><Ticket size={25}/><strong>No bookings in this view</strong><p>Try a different filter or add a new booking.</p></div>}</div></div>;
}
