'use client';

import { ArrowDownRight, ArrowUpRight, Plus } from 'lucide-react';
import type { TripDay } from '@/lib/types';
import { categoryTotals, dayTotal } from '@/lib/travel-calculations';

const palette: Record<string, string> = { Accommodation:'#c5624d', Transport:'#3f777c', Food:'#d29a52', Attraction:'#687ea5', Activity:'#6f8b5c', Note:'#9b7c9f' };

export function BudgetView({ days, budget, planned, paid }: { days: TripDay[]; budget: number; planned: number; paid: number }) {
  const totals = categoryTotals(days); const remaining = budget - planned;
  return <div className="budget-view"><div className="view-title"><div><p className="eyebrow">TRIP BUDGET</p><h2>Spend with a clear head</h2><p>All amounts shown in your base currency, AUD.</p></div><button className="primary-button"><Plus size={15}/> Add expense</button></div><div className="budget-hero"><div className="budget-ring" style={{ '--progress': `${Math.min(planned / budget * 360, 360)}deg` } as React.CSSProperties}><div><span>Remaining</span><strong>A${remaining.toLocaleString()}</strong><small>of A${budget.toLocaleString()}</small></div></div><div className="budget-numbers"><div><span>Planned</span><strong>A${planned.toLocaleString()}</strong><small><ArrowUpRight size={13}/> 91% of budget</small></div><div><span>Paid so far</span><strong>A${paid.toLocaleString()}</strong><small><ArrowDownRight size={13}/> 60% of planned</small></div></div><div className="budget-note"><span>GOOD TO KNOW</span><strong>You have A${remaining.toLocaleString()} of breathing room.</strong><p>Your current plan stays within budget. Accommodation is your largest category.</p></div></div><div className="budget-grid"><section className="category-card"><div className="card-title"><div><p className="eyebrow">BY CATEGORY</p><h3>Where it’s going</h3></div><span>A${Object.values(totals).reduce((a,b)=>a+b,0).toLocaleString()}</span></div>{Object.entries(totals).map(([category,total]) => <div className="category-row" key={category}><span className="category-swatch" style={{ background: palette[category] ?? '#888' }}/><strong>{category}</strong><div><i style={{ width:`${Math.min(total / Math.max(...Object.values(totals)) * 100,100)}%`, background:palette[category] ?? '#888' }}/></div><span>A${total.toLocaleString()}</span></div>)}</section><section className="daily-card"><div className="card-title"><div><p className="eyebrow">DAILY COST</p><h3>At a glance</h3></div><span>Average A$245</span></div><div className="day-bars">{days.map((day) => { const total=dayTotal(day); return <div key={day.id} title={`Day ${day.number}: A$${total}`}><span style={{ height:`${Math.max(12,total/Math.max(...days.map(dayTotal))*100)}%` }} className={total>450?'expensive':''}/><small>D{day.number}</small></div>})}</div><p className="chart-note"><span/> Higher-spend day</p></section></div></div>;
}
