'use client';

import { FileCheck2, FileText, Image, LockKeyhole, Plane, Plus, ShieldCheck, Ticket } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

type WalletDocument={title:string;category:string;type:string;size:string;icon:typeof Plane;color:string};
const initialDocuments:WalletDocument[]=[{title:'Qantas e-ticket',category:'Flights',type:'PDF',size:'284 KB',icon:Plane,color:'#507b85'},{title:'Eko-in confirmation',category:'Accommodation',type:'PDF',size:'146 KB',icon:FileCheck2,color:'#a27c54'},{title:'Travel insurance policy',category:'Insurance',type:'PDF',size:'1.2 MB',icon:ShieldCheck,color:'#687e9d'},{title:'Passport copy',category:'Identity',type:'Image',size:'2.8 MB',icon:Image,color:'#825f86'}];
const formatBytes=(bytes:number)=>bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/(1024*1024)).toFixed(1)} MB`;

export function DocumentsView(){
  const [documents,setDocuments]=useState<WalletDocument[]>(()=>{if(typeof window==='undefined')return initialDocuments;try{const saved=JSON.parse(localStorage.getItem('roamly.wallet.documents.v1')??'[]') as Omit<WalletDocument,'icon'>[];return saved.length?saved.map((item)=>({...item,icon:item.type==='Image'?Image:FileText})):initialDocuments}catch{return initialDocuments}});const [notice,setNotice]=useState('');const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{try{localStorage.setItem('roamly.wallet.documents.v1',JSON.stringify(documents.map(({title,category,type,size,color})=>({title,category,type,size,color}))))}catch{/* local storage may be unavailable */}},[documents]);
  const chooseFile=()=>inputRef.current?.click();
  const addFile=(file?:File)=>{if(!file)return;if(file.size>20*1024*1024){setNotice('That file is larger than 20 MB. Choose a smaller PDF or image.');return}const isImage=file.type.startsWith('image/');setDocuments((items)=>[{title:file.name.replace(/\.[^.]+$/,''),category:'Recently added',type:isImage?'Image':'PDF',size:formatBytes(file.size),icon:isImage?Image:FileText,color:'#4d776c'},...items]);setNotice(`${file.name} was added to this travel wallet.`)};
  return <div className="documents-view"><div className="view-title"><div><p className="eyebrow">TRAVEL WALLET</p><h2>Your essentials, ready when you are</h2><p>Tickets, confirmations and private documents live together.</p></div><button type="button" className="primary-button" onClick={chooseFile}><Plus size={15}/> Upload document</button><input ref={inputRef} hidden type="file" accept="application/pdf,image/*" onChange={(event)=>{addFile(event.target.files?.[0]);event.target.value=''}}/></div>{notice&&<div className="document-notice" role="status"><FileCheck2 size={17}/>{notice}<button type="button" onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}<div className="wallet-security"><LockKeyhole size={19}/><div><strong>Private by default</strong><p>Files are stored securely and only available to travellers with access to this trip.</p></div></div><div className="document-grid">{documents.map(({title,category,type,size,icon:Icon,color})=><article key={`${title}-${size}`}><div className="document-preview" style={{'--doc-color':color} as React.CSSProperties}><Icon size={28}/><span>{type}</span></div><div><small>{category}</small><strong>{title}</strong><p><FileText size={12}/>{type} · {size}</p></div><button type="button" aria-label={`Open ${title}`} onClick={()=>setNotice(`${title} is ready in your travel wallet.`)}>›</button></article>)}<button type="button" className="document-empty" onClick={chooseFile}><span><Ticket size={23}/></span><strong>Add a ticket or confirmation</strong><p>PDF or image up to 20 MB</p></button></div></div>}
