import type { Booking, ItineraryEvent, SavedPlace, SectionTrip, Segment, Trip, TripDay } from './types';

const sectionEvent = (dayId:string, id:string, sortOrder:number, event:Partial<ItineraryEvent> & Pick<ItineraryEvent,'title'|'category'>):ItineraryEvent => ({
  id, dayId, timePrecision:event.time?'exact':'unscheduled', estimatedCost:0, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder, ...event,
});

export const zhangjiajieSectionTrip:SectionTrip = {
  id:'section-zhangjiajie-5-day',
  name:'Zhangjiajie 5-Day Itinerary',
  description:'Four nights based in Wulingyuan, followed by Fenghuang Ancient Town. Avoid weekends. Working budget: A$1,000, or about A$700 with a guided-tour allocation.',
  segments:[
    {id:'section-zjj-wulingyuan',city:'Wulingyuan',country:'China',startDay:1,endDay:4,color:'#356f64',latitude:29.3457,longitude:110.5504,summary:'The practical base for Zhangjiajie National Forest Park, Baofeng Lake and the Grand Canyon.',highlights:['Stay here for four nights','Start park days early','Avoid weekends and major public holidays']},
    {id:'section-zjj-fenghuang',city:'Fenghuang',country:'China',startDay:5,endDay:5,color:'#b8684f',latitude:27.9483,longitude:109.5996,summary:'A lantern-lit ancient town on the Tuojiang River, ideal for a slow afternoon and full riverside evening.',highlights:['Cross Hong Bridge','Watch sunset from Nanhua Bridge','Take the night cruise']},
  ],
  days:[
    {id:'section-zjj-day-1',number:1,date:'Day 1',title:'Arrive & settle into Wulingyuan',segmentId:'section-zjj-wulingyuan',events:[
      sectionEvent('section-zjj-day-1','section-zjj-d1-budget',0,{title:'Trip plan, budget & weekend warning',category:'Note',description:'Do not schedule the major park days on a weekend. Working trip budget is A$1,000; allow roughly A$700 if using a guided tour.',details:['Avoid weekends','A$1,000 working budget','A$700 guided-tour allocation']}),
      sectionEvent('section-zjj-day-1','section-zjj-d1-arrival',1,{title:'Zhangjiajie Airport → Wulingyuan',category:'Transport',subcategory:'Airport transfer',time:'20:00',origin:'Zhangjiajie Hehua International Airport',destination:'Wulingyuan',transportMode:'rental_car',duration:'45–60 min',description:'Arrive by 8:00 PM and transfer directly to the hotel in Wulingyuan.'}),
      sectionEvent('section-zjj-day-1','section-zjj-d1-hotel',2,{title:'Wulingyuan hotel base',category:'Accommodation',subcategory:'Four-night base',time:'21:00',location:'Wulingyuan, Zhangjiajie',duration:'4 nights',description:'Use one Wulingyuan hotel as the base for Nights 1–4 to minimise packing and daily transfers.',bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-1','section-zjj-d1-evening',3,{title:'Xibu Street & Suoxiyu riverside walk',category:'Activity',subcategory:'Easy evening walk',time:'21:30',location:'Xibu Street and Suoxiyu River',description:'If energy allows, get a first taste of Wulingyuan at its main night spot and take a gentle walk beside the river.',details:['Xibu Street','Suoxiyu River','Keep the first night easy']}),
    ]},
    {id:'section-zjj-day-2',number:2,date:'Day 2',title:'Golden Whip Stream & Baofeng Lake',segmentId:'section-zjj-wulingyuan',events:[
      sectionEvent('section-zjj-day-2','section-zjj-d2-stream',0,{title:'Golden Whip Stream',category:'Attraction',subcategory:'Forest walk',time:'08:00',location:'Zhangjiajie National Forest Park',duration:'4 hours',description:'Taxi or walk to the Forest Park East Gate, then take the eco-bus to the Golden Whip Stream area. Walk a peaceful section rather than forcing the full length.',details:['Clear water and dramatic cliffs','Quiet forest trail','Possible monkey sightings','Finish around noon']}),
      sectionEvent('section-zjj-day-2','section-zjj-d2-rest',1,{title:'Hotel rest and reset',category:'Note',time:'12:30',location:'Wulingyuan hotel',duration:'Until 2:00 PM',description:'Return to the hotel for lunch, rest and a refresh before the lighter afternoon.'}),
      sectionEvent('section-zjj-day-2','section-zjj-d2-lake',2,{title:'Baofeng Lake boat ride',category:'Attraction',subcategory:'Scenic boat',time:'14:30',location:'Baofeng Lake',duration:'1–1.5 hours',description:'Take the short scenic boat ride, then return to Wulingyuan with time to rest before the evening.',bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-2','section-zjj-d2-night',3,{title:'Wulingyuan night vibe',category:'Activity',subcategory:'Evening in town',time:'18:00',location:'Xibu Street and Suoxiyu River',description:'Dinner, an unhurried Xibu Street stroll and the riverside walk. A foot massage is an optional finish.',details:['Dinner in Wulingyuan','Xibu Street','Suoxiyu riverside','Optional foot massage']}),
      sectionEvent('section-zjj-day-2','section-zjj-d2-show',4,{title:'Charming Xiangxi Show',category:'Attraction',subcategory:'Cultural show',time:'19:20',location:'Wulingyuan',duration:'1h 40m',description:'Evening performance scheduled for approximately 7:20–9:00 PM. Reserve tickets in advance.',bookingStatus:'Need to Book'}),
    ]},
    {id:'section-zjj-day-3',number:3,date:'Day 3',title:'Avatar mountains, Tianzi & Ten-Mile Gallery',segmentId:'section-zjj-wulingyuan',events:[
      sectionEvent('section-zjj-day-3','section-zjj-d3-yuanjiajie',0,{title:'Bailong Elevator & Yuanjiajie',category:'Attraction',subcategory:'Avatar Mountain area',time:'07:30',location:'Yuanjiajie Scenic Area',duration:'2–2.5 hours',description:'Enter early via the Forest Park East Gate, take the eco-bus to Bailong Elevator and ride to Yuanjiajie’s top platform.',details:['Hallelujah Mountain','First Bridge Under Heaven','Enchanting Platform','Back Garden'],bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-3','section-zjj-d3-tianzi',1,{title:'Tianzi Mountain viewpoints',category:'Attraction',subcategory:'Mountain viewpoints',time:'11:00',location:'Tianzi Mountain',duration:'1–1.5 hours',description:'Take the 20–30 minute eco-bus from Yuanjiajie and explore the headline viewpoints.',details:['Imperial Brush Peak','Helong Park','Fairy Peaks','Sea of Clouds if weather allows']}),
      sectionEvent('section-zjj-day-3','section-zjj-d3-gallery',2,{title:'Ten-Mile Gallery scenic train',category:'Attraction',subcategory:'Scenic railway',time:'13:30',location:'Shili Gallery',duration:'1–1.5 hours',description:'Eco-bus down to Ten-Mile Gallery at the base of Tianzi Mountain, then use the mini scenic train for the rock formations.',details:['Old Man Gathering Herbs','Three Sisters Peak','Mini scenic train'],bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-3','section-zjj-d3-return',3,{title:'Return to Wulingyuan & recover',category:'Activity',subcategory:'Rest evening',time:'16:30',location:'Wulingyuan',description:'Eco-bus out and taxi back to the hotel, aiming to arrive around 4–5 PM. Rest; a foot massage or spa is strongly recommended after the park day.',details:['Early dinner','Rest tired legs','Optional foot massage or spa']}),
    ]},
    {id:'section-zjj-day-4',number:4,date:'Day 4',title:'Glass Bridge & Tianmen Mountain',segmentId:'section-zjj-wulingyuan',events:[
      sectionEvent('section-zjj-day-4','section-zjj-d4-bridge',0,{title:'Grand Canyon Glass Bridge',category:'Attraction',subcategory:'Glass bridge',time:'08:30',location:'Zhangjiajie Grand Canyon',duration:'2 hours',description:'Taxi 25–30 minutes from Wulingyuan. Enter around 9:00 AM, cross the bridge and take photos; skip the canyon hike to protect the afternoon.',details:['Bridge entry 9:00–10:30','Skip canyon hike','Leave for the city by 10:30'],bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-4','section-zjj-d4-transfer',1,{title:'Grand Canyon → Zhangjiajie City',category:'Transport',subcategory:'Taxi transfer',time:'10:30',origin:'Zhangjiajie Grand Canyon',destination:'Tianmen Mountain Cable Car Station',transportMode:'rental_car',duration:'45 min',description:'Transfer to the city and fit in a quick lunch before noon.'}),
      sectionEvent('section-zjj-day-4','section-zjj-d4-tianmen',2,{title:'Tianmen Mountain west route',category:'Attraction',subcategory:'Mountain circuit',time:'12:00',location:'Tianmen Mountain',duration:'7 hours',description:'Cable car to the summit, follow the scenic West Route, descend by escalator to Heaven’s Gate and take the shuttle down the 99-bend road.',details:['Glass Skywalk','Ghost Valley Glass Path','Cliff paths','Tianmen Cave','99-bend Road'],bookingStatus:'Need to Book'}),
      sectionEvent('section-zjj-day-4','section-zjj-d4-city',3,{title:'Zhangjiajie City evening options',category:'Activity',subcategory:'Flexible evening',time:'19:15',location:'Zhangjiajie City',description:'Choose a late dinner and taxi back to Wulingyuan, or add one city-night activity if energy allows.',details:['Lishui River Promenade','City food streets','72 Strange Buildings','Tujia Folk Custom Park','Optional Tianmen Fox Fairy Show 8:00–9:30 PM']}),
    ]},
    {id:'section-zjj-day-5',number:5,date:'Day 5',title:'Wulingyuan → Fenghuang Ancient Town',segmentId:'section-zjj-fenghuang',events:[
      sectionEvent('section-zjj-day-5','section-zjj-d5-train',0,{title:'Leave Wulingyuan for Fenghuang',category:'Transport',subcategory:'Train transfer',time:'08:00',origin:'Wulingyuan',destination:'Fenghuang Ancient Town',transportMode:'high_speed_train',description:'Leave Wulingyuan around 8:00 AM, connect to Fenghuang, then have lunch and rest before exploring.'}),
      sectionEvent('section-zjj-day-5','section-zjj-d5-oldtown',1,{title:'Fenghuang old town walk',category:'Activity',subcategory:'Historic walking route',time:'14:00',location:'Fenghuang Ancient Town',duration:'3 hours',description:'Follow the main riverside path and old lanes at an easy pace.',details:['Cross Hong Bridge','Shiban Street','Shen Congwen Former Residence','Yang Family Ancestral Hall']}),
      sectionEvent('section-zjj-day-5','section-zjj-d5-sunset',2,{title:'Nanhua Bridge sunset & lantern hour',category:'Attraction',subcategory:'Sunset viewpoint',time:'18:00',location:'Nanhua Bridge, Fenghuang',description:'Use Nanhua Bridge for sunset and stay as thousands of lanterns transform the riverfront into the evening scene.'}),
      sectionEvent('section-zjj-day-5','section-zjj-d5-cruise',3,{title:'Tuojiang River night cruise',category:'Activity',subcategory:'Night cruise',time:'20:00',location:'Tuojiang River',duration:'About 1 hour',description:'See the illuminated stilt houses from the water, then complete the full riverside night walk.',estimatedCost:36,bookingStatus:'Need to Book',details:['Approx. ¥168','Glowing stilt houses','Full riverside night walk — must do'],links:[{title:'Fenghuang travel inspiration',url:'https://www.youtube.com/watch?v=tNzum0CPAjo',type:'Video',description:'Reference video supplied with the itinerary'}]}),
      sectionEvent('section-zjj-day-5','section-zjj-d5-extension',4,{title:'Optional extension: mist walk, Furong or Chongqing',category:'Note',description:'If adding a sixth day, take a quiet morning mist walk and slow breakfast, then continue by train to Chongqing (about four hours). Furong Ancient Town is another optional add-on via a short train connection.',links:[{title:'Furong Ancient Town inspiration',url:'https://www.youtube.com/watch?v=vqWcwytSiGA',type:'Video',description:'Reference video supplied with the itinerary'}],details:['Traditional Miao dress photos are best in Fenghuang','Allow one more day for a relaxed Fenghuang stay']}),
    ]},
  ],
};

export const chengduSectionTrip:SectionTrip = {
  id:'section-chengdu-2-day',
  name:'Chengdu — 2 Days + Arrival Evening',
  description:'A central-Chengdu base with an easy arrival night, one culture-and-city day, and a panda plus Leshan day before continuing to Xi’an.',
  segments:[
    {id:'section-chengdu-central',city:'Chengdu',country:'China',startDay:1,endDay:3,color:'#b2674f',latitude:30.5728,longitude:104.0668,summary:'Stay around Tianfu Square, Taikoo Li or Chunxi Road for a walkable base with strong metro connections.',highlights:['Tianfu Square','Taikoo Li and Chunxi Road','Central hotel near a metro line','Modern and traditional photo opportunities']},
  ],
  days:[
    {id:'section-chengdu-day-0',number:1,date:'Arrival evening',title:'Arrive by 5 PM & Chengdu after dark',segmentId:'section-chengdu-central',events:[
      sectionEvent('section-chengdu-day-0','section-chengdu-d0-arrival',0,{title:'Arrive in Chengdu & transfer to hotel',category:'Transport',subcategory:'Arrival transfer',time:'17:00',destination:'Central Chengdu',transportMode:'train',description:'Take a taxi or metro to a hotel near Tianfu Square, Taikoo Li, Chunxi Road or Kuanzhai Alley, then check in and rest.'}),
      sectionEvent('section-chengdu-day-0','section-chengdu-d0-hotel',1,{title:'Central Chengdu hotel',category:'Accommodation',subcategory:'Central base',time:'18:00',location:'Tianfu Square / Taikoo Li / Chunxi Road',duration:'3 nights',description:'Choose a walkable hotel close to the metro for easy city sightseeing and the early guided-tour pickup.',bookingStatus:'Need to Book'}),
      sectionEvent('section-chengdu-day-0','section-chengdu-d0-panda',2,{title:'IFC selfie panda',category:'Attraction',subcategory:'City icon',time:'18:30',location:'Chengdu IFS, Chunxi Road',description:'Stop for the famous climbing-panda statue and city photos before the night walk.'}),
      sectionEvent('section-chengdu-day-0','section-chengdu-d0-night',3,{title:'Chunxi Road & Taikoo Li night walk',category:'Activity',subcategory:'Night photography',time:'19:00',location:'Chunxi Road and Taikoo Li',description:'Take an easy first-night walk through the bright shopping streets, photograph Taikoo Li after dark and have dinner nearby.',details:['Chunxi Road','Taikoo Li night photography','Dinner','Keep the evening relaxed']}),
    ]},
    {id:'section-chengdu-day-1',number:2,date:'Day 1',title:'Old lanes, tea culture & city lights',segmentId:'section-chengdu-central',events:[
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-kuanzhai',0,{title:'Kuanzhai Alleys & traditional dress photos',category:'Activity',subcategory:'Historic lanes and portraits',time:'09:30',location:'Kuanzhai Xiangzi',duration:'2–3 hours',description:'Explore the restored Qing-era Wide and Narrow Alleys, try local snacks and rent traditional clothing for a modern-and-traditional Chengdu photo session.',details:['Traditional dress rental','Photos in the old lanes','Snacks and boutiques','Return the clothes later']}),
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-park',1,{title:'People’s Park & Heming Teahouse',category:'Activity',subcategory:'Tea and local life',time:'12:30',location:'People’s Park, Chengdu',duration:'1.5–2 hours',description:'Slow down in Renmin Park among dancing and mahjong, then have tea at the well-known Heming Teahouse.',details:['Garden walk','Watch local mahjong','Tea at Heming Teahouse']}),
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-books',2,{title:'Taikoo Li bookshops & design stops',category:'Attraction',subcategory:'Books and architecture',time:'15:00',location:'Taikoo Li and nearby central Chengdu',description:'Return toward Taikoo Li for the spiral-walkway Zhong Shuge Bookstore, Fang Suo Commune bookshop café and the Tower of Life.',details:['Zhong Shuge spiral walkway','Fang Suo Commune café','Tower of Life','Taikoo Li shopping street']}),
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-jinli',3,{title:'Dinner at Jinli Ancient Street',category:'Food',subcategory:'Sichuan street food',time:'17:30',location:'Jinli Ancient Street',description:'Try a small selection of Chengdu favourites before the evening show.',details:['Dan dan noodles','Spicy rabbit head','Sweet rice-wine balls']}),
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-opera',4,{title:'Sichuan Opera face-changing show',category:'Attraction',subcategory:'Live performance',time:'19:30',location:'Shufeng Yayun Theatre',duration:'1h 30m',description:'Watch the classic face-changing performance from approximately 7:30–9:00 PM.',bookingStatus:'Need to Book'}),
      sectionEvent('section-chengdu-day-1','section-chengdu-d1-towers',5,{title:'Tianfu Twin Towers light show',category:'Attraction',subcategory:'Beacons of Light',time:'21:15',location:'Tianfu Twin Towers',description:'If timing and energy allow, finish with the Beacons of Light display, then return early because the next morning’s tour pickup is early.'}),
    ]},
    {id:'section-chengdu-day-2',number:3,date:'Day 2',title:'Pandas & Leshan Giant Buddha',segmentId:'section-chengdu-central',events:[
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-pandas',0,{title:'Chengdu Panda Base guided visit',category:'Attraction',subcategory:'Guided panda tour',time:'07:00',location:'Chengdu Research Base of Giant Panda Breeding',duration:'Morning',description:'Use the guided pickup for an early visit while the pandas are most active, then return toward Chengdu around midday.',estimatedCost:62,bookingStatus:'Need to Book',details:['A$62 tour estimate','Early pickup','Morning panda activity'],links:[{title:'Panda Base / Leshan tour option',url:'https://www.getyourguide.com/en-au/chengdu-l1697/panda-baseleshan-buddha-day-tour-or-half-day-panda-tour-t162632/?ranking_uuid=bef29d54-0994-41ae-b5e8-afee6c950822',type:'Tour',description:'Guided tour reference supplied with the itinerary'}]}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-lunch',1,{title:'Quick lunch before Leshan',category:'Food',time:'12:00',location:'Chengdu East Railway Station or Panda Base area',description:'Keep lunch efficient so there is enough time for the train and the Leshan scenic area.'}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-train',2,{title:'Chengdu → Leshan',category:'Transport',subcategory:'High-speed train',time:'13:00',origin:'Chengdu East Railway Station',destination:'Leshan Station',transportMode:'high_speed_train',duration:'About 40 min',description:'On arrival, take a 10–15 minute taxi from Leshan Station to the Giant Buddha scenic area.',bookingStatus:'Need to Book'}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-buddha',3,{title:'Leshan Giant Buddha',category:'Attraction',subcategory:'UNESCO heritage visit',time:'14:15',location:'Leshan Giant Buddha Scenic Area',duration:'3–4 hours',description:'Explore the cliffside site and, if conditions and timing work, add the boat ride for the full-body river view.',details:['Cliff path beside the Buddha','See the rivers meet','Boat ride for full-body view'],bookingStatus:'Need to Book'}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-return',4,{title:'Leshan → Chengdu',category:'Transport',subcategory:'Return train',time:'18:00',origin:'Leshan Station',destination:'Chengdu',transportMode:'high_speed_train',duration:'About 40 min',description:'Taxi back to Leshan Station and take the high-speed train to Chengdu.',bookingStatus:'Need to Book'}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-evening',5,{title:'Final Chengdu evening',category:'Activity',subcategory:'Flexible night',time:'20:00',location:'Taikoo Li / Tianfu Square / Chunxi Road',description:'Have dinner near the hotel, then choose a gentle city walk, Chengdu vintage shops or a large bookstore before resting.',details:['Dinner near the hotel','Vintage shops','Largest bookstore option','Tianfu Square or Chunxi Road walk']}),
      sectionEvent('section-chengdu-day-2','section-chengdu-d2-onward',6,{title:'Next morning: Chengdu → Xi’an',category:'Note',description:'Leave Chengdu in the morning for Xi’an. Keep the night before light and confirm the station, train time and hotel checkout arrangements.',bookingStatus:'Need to Book'}),
    ]},
  ],
};

export const demoTrips: Trip[] = [
  { id:'japan', name:'Japan in Spring', dates:'12–26 May 2027', startDate:'2027-05-12', endDate:'2027-05-26', duration:15, route:'Tokyo → Koyasan → Kyoto → Osaka → Onomichi → Hiroshima', countries:['Japan'], status:'Planning', budget:7000, planned:6340, paid:3820, progress:78, travellers:['Pasindu'], cover:'japan' },
  { id:'alpine', name:'The Alpine Arc', dates:'5–25 Sep 2027', startDate:'2027-09-05', endDate:'2027-09-25', duration:21, route:'Milan → Lucerne → Paris', countries:['Italy','Switzerland','France'], status:'Idea', budget:9200, planned:3180, paid:1200, progress:35, travellers:['Pasindu','Maya'], cover:'alps' },
  { id:'great-ocean', name:'Great Ocean Road', dates:'14–17 Nov 2026', startDate:'2026-11-14', endDate:'2026-11-17', duration:4, route:'Melbourne → Lorne → Port Campbell', countries:['Australia'], status:'Booked', budget:1800, planned:1620, paid:1410, progress:90, travellers:['Pasindu','Alex','Sam'], cover:'coast' },
];

export const japanSegments: Segment[] = [
  { id:'tokyo', city:'Tokyo', country:'Japan', startDay:1, endDay:4, color:'#c85f49', latitude:35.6762, longitude:139.6503, imageUrl:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=85', summary:'A many-layered capital where neighbourhood food, design, shrines and rail lines make every day feel different.', highlights:['Base yourself near a useful rail line','Book headline attractions before arrival','Leave time to explore one neighbourhood slowly'], sourceUrl:'https://www.gotokyo.org/en/' },
  { id:'koyasan', city:'Koyasan', country:'Japan', startDay:5, endDay:5, color:'#a17c53', latitude:34.2125, longitude:135.586, imageUrl:'https://images.unsplash.com/photo-1672899939135-4bca7071f771?auto=format&fit=crop&w=1600&q=85', summary:'A forested temple settlement and centre of Shingon Buddhism, best experienced with a temple stay and an unhurried walk.', highlights:['Pack an overnight bag for the mountain','Join the morning service if offered','Respect the sacred atmosphere at Okunoin'], sourceUrl:'https://www.koyasan.or.jp/english/' },
  { id:'kyoto', city:'Kyoto', country:'Japan', startDay:6, endDay:7, color:'#617c55', latitude:35.0116, longitude:135.7681, imageUrl:'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg', summary:'Historic lanes, temples, gardens and exceptional food reward early starts and a plan grouped by neighbourhood.', highlights:['Visit popular temples early','Use trains for Fushimi Inari','Avoid eating while walking through Nishiki Market'], sourceUrl:'https://kyoto.travel/en' },
  { id:'osaka', city:'Osaka', country:'Japan', startDay:8, endDay:9, color:'#3f777c', latitude:34.6937, longitude:135.5023, imageUrl:'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=1600&q=85', summary:'A lively, food-forward city with easy rail connections, bright night streets and a famously relaxed personality.', highlights:['Come hungry for a food crawl','Use an IC card for local transport','Pair major sights with nearby neighbourhoods'], sourceUrl:'https://osaka-info.jp/en/' },
  { id:'onomichi', city:'Onomichi', country:'Japan', startDay:10, endDay:11, color:'#5d7094', latitude:34.4089, longitude:133.2049, imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1600&q=85', summary:'A compact hillside port of temple paths, sea views and the gateway to the Shimanami Kaido cycling route.', highlights:['Travel light on the hills','Reserve bicycles in advance','Check ferry and luggage options'], sourceUrl:'https://www.ononavi.jp/english/' },
  { id:'hiroshima', city:'Hiroshima', country:'Japan', startDay:12, endDay:15, color:'#805c87', latitude:34.3853, longitude:132.4553, imageUrl:'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=85', summary:'A thoughtful final stop combining modern city life, profound history and an easy day trip to Miyajima.', highlights:['Allow quiet time at Peace Memorial Park','Check Miyajima tide times','Try Hiroshima-style okonomiyaki'], sourceUrl:'https://dive-hiroshima.com/en/' },
];

export const japanDays: TripDay[] = [
  { id:'day-5', number:5, date:'Monday, 16 May', title:'Tokyo → Koyasan', segmentId:'koyasan', events:[
    { id:'e-1', dayId:'day-5', title:'Tokyo Station → Shin-Osaka', category:'Transport', subcategory:'High-speed train', time:'07:30', timePrecision:'exact', origin:'Tokyo Station', destination:'Shin-Osaka', transportMode:'high_speed_train', provider:'JR Central', serviceNumber:'Nozomi 209', duration:'3h 05m', estimatedCost:194, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', description:'Green Car · Seat preference: window', links:[{ title:'Book with SmartEX', url:'https://smart-ex.jp/en/', type:'Ticket', description:'Official booking site for this train' }], sortOrder:0 },
    { id:'e-2', dayId:'day-5', title:'Namba → Gokurakubashi', category:'Transport', subcategory:'Train', time:'12:00', timePrecision:'approximate', origin:'Namba', destination:'Gokurakubashi', transportMode:'train', provider:'Nankai Railway', duration:'1h 35m', estimatedCost:22, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-3', dayId:'day-5', title:'Eko-in Temple Stay', category:'Accommodation', subcategory:'Temple stay', time:'14:30', timePrecision:'exact', location:'Eko-in, Koyasan', latitude:34.2142, longitude:135.5901, description:'Stay in a working Buddhist temple with traditional shojin ryori meals and the option to join morning practice.', details:['Dinner included','Breakfast included','Morning Buddhist service','Meditation'], imageUrl:'https://www.ekoin.jp/wp-content/uploads/2021/11/twitter_card.jpg', imageAlt:'Eko-in temple lodging at Koyasan', visitorInfo:[{label:'Check-in',value:'From 14:00'},{label:'Meals',value:'Shojin ryori dinner and breakfast'},{label:'Planning',value:'Reservations open up to 11 months ahead'}], highlights:['Arrive before dinner service','Bring warm layers outside summer','Ask about meditation, sutra copying and the night tour'], sourceUrl:'https://www.ekoin.jp/en/', sourceLabel:'Eko-in official guest information', estimatedCost:210, currency:'AUD', bookingStatus:'Booked', paymentStatus:'Paid', links:[{ title:'Eko-in official information', url:'https://www.ekoin.jp/en/', type:'Official Website', description:'Property details, access and guest information' }], sortOrder:2 },
    { id:'e-4', dayId:'day-5', title:'Okunoin Night Tour', category:'Attraction', subcategory:'Guided tour', time:'18:45', timePrecision:'exact', location:'Okunoin Cemetery', latitude:34.2163, longitude:135.6031, duration:'1h 20m', description:'A guided evening walk through the cedar forest and sacred cemetery leading toward Kobo Daishi\'s mausoleum.', imageUrl:'https://images.unsplash.com/photo-1672899939135-4bca7071f771?auto=format&fit=crop&w=1600&q=85', imageAlt:'Moss-covered stone memorials in the forest at Koyasan', highlights:['Wear quiet, comfortable shoes','Photography etiquette can vary in sacred areas','Confirm the meeting point with your temple lodging'], sourceUrl:'https://www.koyasan.or.jp/english/', sourceLabel:'Koyasan official visitor information', estimatedCost:60, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', links:[{ title:'Reserve night tour', url:'https://www.koyasan.or.jp/english/', type:'Booking', description:'Tour availability and reservation details' }], sortOrder:3 },
  ]},
  { id:'day-6', number:6, date:'Tuesday, 17 May', title:'First light in Kyoto', segmentId:'kyoto', events:[
    { id:'e-5', dayId:'day-6', title:'Koyasan → Kyoto', category:'Transport', subcategory:'Train', time:'08:15', timePrecision:'exact', origin:'Koyasan', destination:'Kyoto', transportMode:'train', duration:'2h 48m', estimatedCost:36, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:0 },
    { id:'e-6', dayId:'day-6', title:'Cross Hotel Kyoto', category:'Accommodation', subcategory:'Hotel', time:'14:00', timePrecision:'exact', location:'Kawaramachi, Kyoto', latitude:35.0087, longitude:135.7694, description:'Standard king room · 2 nights', estimatedCost:310, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-7', dayId:'day-6', title:'Gion evening walk', category:'Activity', subcategory:'Walking', time:'17:00', timePrecision:'approximate', location:'Gion, Kyoto', latitude:35.0037, longitude:135.7788, duration:'1h 30m', estimatedCost:0, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:2 },
    { id:'e-8', dayId:'day-6', title:'Dinner at Gion Kappa', category:'Food', subcategory:'Restaurant', time:'19:30', timePrecision:'exact', location:'Gion, Kyoto', estimatedCost:58, currency:'AUD', bookingStatus:'Reserved', paymentStatus:'Not Paid', sortOrder:3 },
  ]},
  { id:'day-7', number:7, date:'Wednesday, 18 May', title:'Shrines, lanes & markets', segmentId:'kyoto', events:[
    { id:'e-9', dayId:'day-7', title:'Fushimi Inari at sunrise', category:'Attraction', subcategory:'Shrine', time:'06:45', timePrecision:'exact', location:'Fushimi Inari Taisha', latitude:34.9671, longitude:135.7727, description:'Walk beneath the vermilion torii gates before the busiest part of the day and continue uphill as energy allows.', imageUrl:'https://inari.jp/en/wp-content/uploads/2015/09/main_img5.jpg', imageAlt:'Vermilion torii gates at Fushimi Inari Taisha', visitorInfo:[{label:'Access',value:'JR Inari Station or Keihan Fushimi-Inari Station'},{label:'Address',value:'68 Fukakusa Yabunouchi-cho, Fushimi-ku'}], highlights:['Public transport is strongly recommended','Start early for a calmer walk','Allow two to three hours for the full mountain route'], sourceUrl:'https://inari.jp/en/access/', sourceLabel:'Fushimi Inari Taisha official access guide', estimatedCost:0, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:0 },
    { id:'e-10', dayId:'day-7', title:'Kiyomizu-dera', category:'Attraction', subcategory:'Temple', time:'10:30', timePrecision:'approximate', location:'Higashiyama, Kyoto', latitude:34.9949, longitude:135.785, description:'A celebrated hillside temple with a broad wooden stage, city views and an atmospheric approach through Higashiyama.', imageUrl:'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg', imageAlt:'Kiyomizu-dera temple overlooking Kyoto', visitorInfo:[{label:'Opens',value:'06:00 daily'},{label:'Closing',value:'Varies by season'},{label:'Address',value:'1-294 Kiyomizu, Higashiyama-ku'}], highlights:['Check the official calendar for seasonal closing times','Combine with the preserved lanes of Higashiyama','Use the temple’s official access guidance when mapping'], sourceUrl:'https://www.kiyomizudera.or.jp/en/location/', sourceLabel:'Kiyomizu-dera official visitor guide', estimatedCost:6, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-11', dayId:'day-7', title:'Nishiki Market lunch', category:'Food', subcategory:'Market', time:'13:30', timePrecision:'approximate', location:'Nishiki Market', latitude:35.005, longitude:135.7649, description:'Explore Kyoto\'s historic kitchen: a compact covered arcade lined with more than 100 food shops and stalls.', imageUrl:'https://asset.japan.travel/image/upload/v1648006915/kyoto/H_00480_001.jpg', imageAlt:'Food stalls in Kyoto Nishiki Market', visitorInfo:[{label:'Length',value:'About 400 metres'},{label:'Best time',value:'Around 11:00 for the widest choice'},{label:'Style',value:'Market snacks, ingredients and souvenirs'}], highlights:['Do not eat while walking','Stand at the shop or use its designated eating space','Many vendors close by early evening'], sourceUrl:'https://www.japan.travel/en/spot/1174/', sourceLabel:'JNTO official Nishiki Market guide', estimatedCost:32, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:2 },
  ]},
];

export const japanBookings: Booking[] = [
  { id:'b1', title:'International flight', category:'Flight', provider:'Qantas', reference:'QF8S2A', status:'Paid', paymentStatus:'Paid', cost:1550, currency:'AUD' },
  { id:'b2', title:'Tokyo hotel', category:'Accommodation', provider:'Hotel Groove', reference:'HG-27712', status:'Booked', paymentStatus:'Deposit paid', cancellationDeadline:'Free cancellation until 4 May', cost:760, currency:'AUD' },
  { id:'b3', title:'Eko-in Temple Stay', category:'Accommodation', provider:'Eko-in', reference:'EK-4568', status:'Paid', paymentStatus:'Paid', cost:210, currency:'AUD' },
  { id:'b4', title:'Kyoto hotel', category:'Accommodation', status:'Need to Book', paymentStatus:'Not paid', deadline:'Due 4 Sep', cost:310, currency:'AUD' },
  { id:'b5', title:'Tokyo → Shin-Osaka', category:'High-speed train', provider:'SmartEX', status:'Need to Book', paymentStatus:'Not paid', deadline:'Booking opens in 8 days', cost:194, currency:'AUD' },
  { id:'b6', title:'Okunoin Night Tour', category:'Attraction', status:'Need to Book', paymentStatus:'Not paid', cost:60, currency:'AUD' },
  { id:'b7', title:'Shimanami Kaido bicycle', category:'Rental', status:'Shortlisted', paymentStatus:'Not paid', cost:42, currency:'AUD' },
];

export const savedPlaces: SavedPlace[] = [
  { id:'s1', title:'teamLab Borderless', category:'Attraction', city:'Tokyo', note:'Best on a weekday morning' },
  { id:'s2', title:'Arashiyama', category:'Place', city:'Kyoto', note:'Could fit early on Day 7' },
  { id:'s3', title:'Nara day trip', category:'Idea', city:'Nara', note:'Keep as optional slow-day alternative' },
  { id:'s4', title:'Himeji Castle', category:'Attraction', city:'Himeji', note:'Possible stop between Osaka and Onomichi' },
];
