import type { Booking, SavedPlace, Segment, Trip, TripDay } from './types';

export const demoTrips: Trip[] = [
  { id:'japan', name:'Japan in Spring', dates:'12–26 May 2027', startDate:'2027-05-12', endDate:'2027-05-26', duration:15, route:'Tokyo → Koyasan → Kyoto → Osaka → Onomichi → Hiroshima', countries:['Japan'], status:'Planning', budget:7000, planned:6340, paid:3820, progress:78, travellers:['Pasindu'], cover:'japan' },
  { id:'alpine', name:'The Alpine Arc', dates:'5–25 Sep 2027', startDate:'2027-09-05', endDate:'2027-09-25', duration:21, route:'Milan → Lucerne → Paris', countries:['Italy','Switzerland','France'], status:'Idea', budget:9200, planned:3180, paid:1200, progress:35, travellers:['Pasindu','Maya'], cover:'alps' },
  { id:'great-ocean', name:'Great Ocean Road', dates:'14–17 Nov 2026', startDate:'2026-11-14', endDate:'2026-11-17', duration:4, route:'Melbourne → Lorne → Port Campbell', countries:['Australia'], status:'Booked', budget:1800, planned:1620, paid:1410, progress:90, travellers:['Pasindu','Alex','Sam'], cover:'coast' },
];

export const japanSegments: Segment[] = [
  { id:'tokyo', city:'Tokyo', country:'Japan', startDay:1, endDay:4, color:'#c85f49', latitude:35.6762, longitude:139.6503, imageUrl:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=85', summary:'A many-layered capital where neighbourhood food, design, shrines and rail lines make every day feel different.', highlights:['Base yourself near a useful rail line','Book headline attractions before arrival','Leave time to explore one neighbourhood slowly'], sourceUrl:'https://www.gotokyo.org/en/' },
  { id:'koyasan', city:'Koyasan', country:'Japan', startDay:5, endDay:5, color:'#a17c53', latitude:34.2125, longitude:135.586, imageUrl:'https://images.unsplash.com/photo-1672899939135-4bca7071f771?auto=format&fit=crop&w=1600&q=85', summary:'A forested temple settlement and centre of Shingon Buddhism, best experienced with a temple stay and an unhurried walk.', highlights:['Pack an overnight bag for the mountain','Join the morning service if offered','Respect the sacred atmosphere at Okunoin'], sourceUrl:'https://www.koyasan.or.jp/english/' },
  { id:'kyoto', city:'Kyoto', country:'Japan', startDay:6, endDay:7, color:'#617c55', latitude:35.0116, longitude:135.7681, imageUrl:'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg', summary:'Historic lanes, temples, gardens and exceptional food reward early starts and a plan grouped by neighbourhood.', highlights:['Visit popular temples early','Use trains for Fushimi Inari','Avoid eating while walking through Nishiki Market'], sourceUrl:'https://kyoto.travel/en' },
  { id:'osaka', city:'Osaka', country:'Japan', startDay:8, endDay:9, color:'#3f777c', latitude:34.6937, longitude:135.5023, imageUrl:'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=1600&q=85', summary:'A lively, food-forward city with easy rail connections, bright night streets and a famously relaxed personality.', highlights:['Come hungry for a food crawl','Use an IC card for local transport','Pair major sights with nearby neighbourhoods'], sourceUrl:'https://osaka-info.jp/en/' },
  { id:'onomichi', city:'Onomichi', country:'Japan', startDay:10, endDay:11, color:'#5d7094', latitude:34.4089, longitude:133.2049, imageUrl:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1600&q=85', summary:'A compact hillside port of temple paths, sea views and the gateway to the Shimanami Kaido cycling route.', highlights:['Travel light on the hills','Reserve bicycles in advance','Check ferry and luggage options'], sourceUrl:'https://www.ononavi.jp/english/' },
  { id:'hiroshima', city:'Hiroshima', country:'Japan', startDay:12, endDay:15, color:'#805c87', latitude:34.3853, longitude:132.4553, imageUrl:'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=85', summary:'A thoughtful final stop combining modern city life, profound history and an easy day trip to Miyajima.', highlights:['Allow quiet time at Peace Memorial Park','Check Miyajima tide times','Try Hiroshima-style okonomiyaki'], sourceUrl:'https://dive-hiroshima.com/en/' },
];

export const japanDays: TripDay[] = [
  { id:'day-5', number:5, date:'Monday, 16 May', title:'Tokyo → Koyasan', segmentId:'koyasan', events:[
    { id:'e-1', dayId:'day-5', title:'Tokyo Station → Shin-Osaka', category:'Transport', subcategory:'High-speed train', time:'07:30', timePrecision:'exact', origin:'Tokyo Station', destination:'Shin-Osaka', transportMode:'high_speed_train', provider:'JR Central', serviceNumber:'Nozomi 209', duration:'3h 05m', estimatedCost:194, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', description:'Green Car · Seat preference: window', links:[{ title:'Book with SmartEX', url:'https://smart-ex.jp/en/', type:'Ticket', description:'Official booking site for this train' }], sortOrder:0 },
    { id:'e-2', dayId:'day-5', title:'Namba → Gokurakubashi', category:'Transport', subcategory:'Train', time:'12:00', timePrecision:'approximate', origin:'Namba', destination:'Gokurakubashi', transportMode:'train', provider:'Nankai Railway', duration:'1h 35m', estimatedCost:22, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-3', dayId:'day-5', title:'Eko-in Temple Stay', category:'Accommodation', subcategory:'Temple stay', time:'14:30', timePrecision:'exact', location:'Eko-in, Koyasan', latitude:34.2142, longitude:135.5901, description:'Stay in a working Buddhist temple with traditional shojin ryori meals and the option to join morning practice.', details:['Dinner included','Breakfast included','Morning Buddhist service','Meditation'], imageUrl:'https://www.ekoin.jp/wp-content/uploads/2021/11/twitter_card.jpg', imageAlt:'Eko-in temple lodging at Koyasan', visitorInfo:[{label:'Check-in',value:'From 14:00'},{label:'Meals',value:'Shojin ryori dinner and breakfast'},{label:'Planning',value:'Reservations open up to 11 months ahead'}], highlights:['Arrive before dinner service','Bring warm layers outside summer','Ask about meditation, sutra copying and the night tour'], sourceUrl:'https://www.ekoin.jp/en/', sourceLabel:'Eko-in official guest information', estimatedCost:210, currency:'AUD', bookingStatus:'Booked', paymentStatus:'Paid', links:[{ title:'Eko-in official information', url:'https://www.ekoin.jp/en/', type:'Official Website', description:'Property details, access and guest information' }], sortOrder:2 },
    { id:'e-4', dayId:'day-5', title:'Okunoin Night Tour', category:'Attraction', subcategory:'Guided tour', time:'18:45', timePrecision:'exact', location:'Okunoin Cemetery', latitude:34.2163, longitude:135.6031, duration:'1h 20m', description:'A guided evening walk through the cedar forest and sacred cemetery leading toward Kobo Daishi\'s mausoleum.', imageUrl:'https://images.unsplash.com/photo-1672899939135-4bca7071f771?auto=format&fit=crop&w=1600&q=85', imageAlt:'Moss-covered stone memorials in the forest at Koyasan', highlights:['Wear quiet, comfortable shoes','Photography etiquette can vary in sacred areas','Confirm the meeting point with your temple lodging'], sourceUrl:'https://www.koyasan.or.jp/english/', sourceLabel:'Koyasan official visitor information', estimatedCost:60, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', links:[{ title:'Reserve night tour', url:'https://www.koyasan.or.jp/english/', type:'Booking', description:'Tour availability and reservation details' }], sortOrder:3 },
  ]},
  { id:'day-6', number:6, date:'Tuesday, 17 May', title:'First light in Kyoto', segmentId:'kyoto', events:[
    { id:'e-5', dayId:'day-6', title:'Koyasan → Kyoto', category:'Transport', subcategory:'Train', time:'08:15', timePrecision:'exact', origin:'Koyasan', destination:'Kyoto', transportMode:'train', duration:'2h 48m', estimatedCost:36, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:0 },
    { id:'e-6', dayId:'day-6', title:'Cross Hotel Kyoto', category:'Accommodation', subcategory:'Hotel', time:'14:00', timePrecision:'exact', location:'Kawaramachi, Kyoto', latitude:35.0087, longitude:135.7694, description:'Standard king room · 2 nights', estimatedCost:310, currency:'AUD', bookingStatus:'Need to Book', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-7', dayId:'day-6', title:'Gion evening walk', category:'Activity', subcategory:'Walking', time:'17:00', timePrecision:'approximate', location:'Gion, Kyoto', latitude:35.0037, longitude:135.7788, duration:'1h 30m', estimatedCost:0, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:2 },
    { id:'e-8', dayId:'day-6', title:'Dinner at Gion Kappa', category:'Food', subcategory:'Restaurant', time:'19:30', timePrecision:'exact', location:'Gion, Kyoto', estimatedCost:58, currency:'AUD', bookingStatus:'Reserved', paymentStatus:'Not Paid', sortOrder:3 },
  ]},
  { id:'day-7', number:7, date:'Wednesday, 18 May', title:'Shrines, lanes & markets', segmentId:'kyoto', events:[
    { id:'e-9', dayId:'day-7', title:'Fushimi Inari at sunrise', category:'Attraction', subcategory:'Shrine', time:'06:45', timePrecision:'exact', location:'Fushimi Inari Taisha', latitude:34.9671, longitude:135.7727, description:'Walk beneath the vermilion torii gates before the busiest part of the day and continue uphill as energy allows.', imageUrl:'https://inari.jp/en/wp-content/uploads/2015/09/main_img5.jpg', imageAlt:'Vermilion torii gates at Fushimi Inari Taisha', visitorInfo:[{label:'Access',value:'JR Inari Station or Keihan Fushimi-Inari Station'},{label:'Address',value:'68 Fukakusa Yabunouchi-cho, Fushimi-ku'}], highlights:['Public transport is strongly recommended','Start early for a calmer walk','Allow two to three hours for the full mountain route'], sourceUrl:'https://inari.jp/en/access/', sourceLabel:'Fushimi Inari Taisha official access guide', estimatedCost:0, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:0 },
    { id:'e-10', dayId:'day-7', title:'Kiyomizu-dera', category:'Attraction', subcategory:'Temple', time:'10:30', timePrecision:'approximate', location:'Higashiyama, Kyoto', latitude:34.9949, longitude:135.785, description:'A celebrated hillside temple with a broad wooden stage, city views and an atmospheric approach through Higashiyama.', imageUrl:'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg', imageAlt:'Kiyomizu-dera temple overlooking Kyoto', visitorInfo:[{label:'Opens',value:'06:00 daily'},{label:'Closing',value:'Varies by season'},{label:'Address',value:'1-294 Kiyomizu, Higashiyama-ku'}], highlights:['Check the official calendar for seasonal closing times','Combine with the preserved lanes of Higashiyama','Use the temple’s official access guidance when mapping'], sourceUrl:'https://www.kiyomizudera.or.jp/en/location/', sourceLabel:'Kiyomizu-dera official visitor guide', estimatedCost:6, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:1 },
    { id:'e-11', dayId:'day-7', title:'Nishiki Market lunch', category:'Food', subcategory:'Market', time:'13:30', timePrecision:'approximate', location:'Nishiki Market', latitude:35.005, longitude:135.7649, description:'Explore Kyoto\'s historic kitchen: a compact covered arcade lined with more than 100 food shops and stalls.', imageUrl:'https://asset.japan.travel/image/upload/v1648006915/kyoto/H_00480_001.jpg', imageAlt:'Food stalls in Kyoto Nishiki Market', visitorInfo:[{label:'Length',value:'About 400 metres'},{label:'Best time',value:'Around 11:00 for the widest choice'},{label:'Style',value:'Market snacks, ingredients and souvenirs'}], highlights:['Do not eat while walking','Stand at the shop or use its designated eating space','Many vendors close by early evening'], sourceUrl:'https://www.japan.travel/en/spot/1174/', sourceLabel:'JNTO official Nishiki Market guide', estimatedCost:32, currency:'AUD', bookingStatus:'Not Required', paymentStatus:'Not Paid', sortOrder:2 },
  ]},
];

export const japanBookings: Booking[] = [
  { id:'b1', title:'International flight', category:'Flight', provider:'Qantas', reference:'QF8S2A', status:'Paid', paymentStatus:'Paid', cost:1550, currency:'AUD' },
  { id:'b2', title:'Tokyo hotel', category:'Accommodation', provider:'Hotel Groove', reference:'HG-27712', status:'Booked', paymentStatus:'Deposit paid', cancellationDeadline:'Free cancellation until 4 May', cost:760, currency:'AUD' },
  { id:'b3', title:'Eko-in Temple Stay', category:'Accommodation', provider:'Eko-in', reference:'EK-4568', status:'Paid', paymentStatus:'Paid', cost:210, currency:'AUD' },
  { id:'b4', title:'Kyoto hotel', category:'Accommodation', status:'Need to Book', paymentStatus:'Not paid', deadline:'Due 4 Sep', cost:310, currency:'AUD' },
  { id:'b5', title:'Tokyo → Shin-Osaka', category:'High-speed train', provider:'SmartEX', status:'Need to Book', paymentStatus:'Not paid', deadline:'Booking opens in 8 days', cost:194, currency:'AUD' },
  { id:'b6', title:'Okunoin Night Tour', category:'Attraction', status:'Need to Book', paymentStatus:'Not paid', cost:60, currency:'AUD' },
  { id:'b7', title:'Shimanami Kaido bicycle', category:'Rental', status:'Shortlisted', paymentStatus:'Not paid', cost:42, currency:'AUD' },
];

export const savedPlaces: SavedPlace[] = [
  { id:'s1', title:'teamLab Borderless', category:'Attraction', city:'Tokyo', note:'Best on a weekday morning' },
  { id:'s2', title:'Arashiyama', category:'Place', city:'Kyoto', note:'Could fit early on Day 7' },
  { id:'s3', title:'Nara day trip', category:'Idea', city:'Nara', note:'Keep as optional slow-day alternative' },
  { id:'s4', title:'Himeji Castle', category:'Attraction', city:'Himeji', note:'Possible stop between Osaka and Onomichi' },
];
